# =============================================================================
# 비즈니스 관리 시스템 Django 설정
# =============================================================================
# 설명: Django 프로젝트의 모든 설정을 정의하는 메인 설정 파일
# 작성자: 비즈니스 관리 시스템 개발팀
# 버전: 1.0.0
# =============================================================================

"""
Django settings for business_management project.

이 프로젝트는 기업용 업무 관리 시스템으로, 거래처 관리, 근태 관리, 
프로젝트 관리 등 다양한 비즈니스 기능을 제공합니다.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# 경로 관리를 위한 Path 클래스 임포트
from pathlib import Path
# 운영체제 관련 기능 임포트
import os
from django.core.exceptions import ImproperlyConfigured

# =============================================================================
# 기본 경로 설정
# =============================================================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 프로젝트의 기본 디렉토리 경로를 설정합니다.
# 이 경로를 기준으로 모든 파일 경로를 계산합니다.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# 개발 환경 설정
# =============================================================================
# Quick-start development settings - unsuitable for production
# 개발 환경을 위한 빠른 시작 설정 - 운영 환경에는 적합하지 않음
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# =============================================================================
# 보안 설정
# =============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
# 보안 경고: 운영 환경에서 사용되는 시크릿 키를 비밀로 유지하세요!
# Django의 암호화, 세션, CSRF 보호 등에 사용되는 중요한 키입니다.
# 운영 환경에서는 반드시 환경 변수나 별도 파일에서 관리해야 합니다.

# DEBUG may be controlled via environment for CI/production. Default to True for local dev.
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-key-please-change'
    else:
        raise ImproperlyConfigured('The SECRET_KEY environment variable is required in production')

# SECURITY WARNING: don't run with debug turned on in production!
# 보안 경고: 운영 환경에서 디버그 모드를 켜지 마세요!
# DEBUG=True이면 에러 상세 정보가 노출되어 보안에 취약합니다.
# 개발 환경에서는 True, 운영 환경에서는 False로 설정해야 합니다.

# =============================================================================
# 호스트 설정
# =============================================================================
# ALLOWED_HOSTS는 이 Django 사이트가 서비스될 수 있는 호스트명/도메인 목록입니다.
# 개발 환경에서는 localhost와 127.0.0.1을 허용합니다.
# 운영 환경에서는 실제 도메인을 추가해야 합니다.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# =============================================================================
# 애플리케이션 정의
# =============================================================================
# Application definition
# 애플리케이션 정의 - 프로젝트에 포함된 Django 앱 목록
# 등록된 순서대로 로드되며, 의존성이 있는 앱은 먼저 등록해야 합니다.

INSTALLED_APPS = [
    # Django 기본 앱들 - 핵심 기능 제공
    'django.contrib.admin',         # 관리자 사이트 - 데이터베이스 관리 인터페이스
    'django.contrib.auth',          # 인증 시스템 - 사용자 인증 및 권한 관리
    'django.contrib.contenttypes',   # 콘텐츠 타입 프레임워크 - 모델 간 관계 관리
    'django.contrib.sessions',      # 세션 프레임워크 - 사용자 세션 관리
    'django.contrib.messages',      # 메시지 프레임워크
    'django.contrib.staticfiles',   # 정적 파일 관리

    # 프로젝트 특정 앱들 - 비즈니스 로직 구현
    'client_inform',               # 거래처 정보 관리
    'businessStatus',              # 업무 상태 관리
    'commute',                     # 근태 관리
    'home',                        # 홈페이지
    'login',                       # 로그인
    '공지사항',                     # 공지사항 관리
    '기술',                        # 기술 관리
    'utils',                       # 유틸리티 모듈 (캐싱, 보안, 모니터링)
    # 'api',                         # RESTful API
]

# MIDDLEWARE - 요청과 응답 처리 중간에 실행되는 미들웨어 목록
# 요청이 뷰에 도달하기 전과 응답이 클라이언트에 전송되기 전에 실행됩니다.

MIDDLEWARE = [
    # Django 기본 미들웨어
    'django.middleware.security.SecurityMiddleware',              # 보안 관련 미들웨어
    'django.contrib.sessions.middleware.SessionMiddleware',        # 세션 처리
    'django.middleware.common.CommonMiddleware',                  # 공통 미들웨어
    'django.middleware.csrf.CsrfViewMiddleware',                  # CSRF 보호
    'django.contrib.auth.middleware.AuthenticationMiddleware',     # 인증 미들웨어
    'django.contrib.messages.middleware.MessageMiddleware',       # 메시지 처리
    'django.middleware.clickjacking.XFrameOptionsMiddleware',     # 클릭재킹 보호
]

ROOT_URLCONF = 'business_management.urls'
# URL 설정의 최상위 모듈 경로를 지정합니다.

TEMPLATES = [
    # 템플릿 엔진 설정 - HTML 템플릿을 어떻게 렌더링할지 정의
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Django 템플릿 백엔드 사용
        'DIRS': [os.path.join(BASE_DIR, 'templates')],              # 템플릿 디렉토리 경로
        'APP_DIRS': True,                                            # 앱 디렉토리에서 템플릿 검색
        'OPTIONS': {
            # 템플릿 컨텍스트 프로세서 - 모든 템플릿에서 사용할 수 있는 변수들
            'context_processors': [
                'django.template.context_processors.debug',      # 디버그 정보
                'django.template.context_processors.request',    # 요청 객체
                'django.contrib.auth.context_processors.auth',   # 인증 정보
                'django.contrib.messages.context_processors.messages', # 메시지
            ],
        },
    },
]

WSGI_APPLICATION = 'business_management.wsgi.application'
# WSGI 애플리케이션 설정 - 웹 서버와 Django 연결
# NOTE: `DEFAULT_AUTO_FIELD` is set later to the canonical Django value.
# Database
# 데이터베이스 설정 - 개발 환경에서는 SQLite 사용
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Database
# 데이터베이스 설정 - 개발 환경에서는 SQLite 사용
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',    # SQLite 백엔드 사용
        'NAME': BASE_DIR / 'db.sqlite3',          # 데이터베이스 파일 경로
    }
}
# LOGGING is consolidated later in this file; keep a single effective
# LOGGING configuration (defined further below).

# Cache settings - 성능을 위한 캐시 설정
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 3600,
    },
    'template_fragments': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 300,
    },
}

# Security settings
# 보안 설정 - 운영/개발 환경에 따라 일부 값은 동적으로 설정
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
# Cookie security: enable strict/secure cookies in production
if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'    # 정적 파일 URL 접두사
STATICFILES_DIRS = [       # 정적 파일을 저장할 추가 디렉토리
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 명령으로 수집될 파일 저장 위치

# Default primary key field type
# 기본 기본 키 필드 타입 설정
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # 큰 정수 자동 증가 기본 키

# Media files
# 미디어 파일 설정 - 사용자가 업로드한 파일들
MEDIA_URL = '/media/'       # 미디어 파일 URL 접두사
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 미디어 파일 저장 경로

# Internationalization
# 국제화 설정
LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True

# Additional security settings are handled above (cookie security is set
# conditionally based on DEBUG). Do not duplicate here.

# Logging configuration
# 로깅 설정 - 애플리케이션의 동작을 기록하는 설정
LOGGING = {
    'version': 1,  # 로깅 딕셔너리 버전
    'disable_existing_loggers': False,  # 기존 로거 비활성화 여부
    'formatters': {  # 로그 메시지 포맷 설정
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {  # 로그 핸들러 - 로그를 어디에 출력할지 정의
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {  # 최상위 로거 설정
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {  # 특정 로거 설정
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'business_management': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Email settings
# 이메일 설정 - 비밀번호 재설정, 알림 등에 사용
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 개발 환경에서는 콘솔로 출력
EMAIL_HOST = 'smtp.gmail.com'      # SMTP 서버 호스트
EMAIL_PORT = 587                   # SMTP 포트
EMAIL_USE_TLS = True               # TLS 암호화 사용
EMAIL_HOST_USER = ''               # SMTP 사용자 이름
EMAIL_HOST_PASSWORD = ''           # SMTP 비밀번호
DEFAULT_FROM_EMAIL = 'noreply@yourdomain.com'  # 기본 발신자 이메일

# Celery settings
# Celery 설정 - 비동기 작업 처리를 위한 설정
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # 메시지 브로커 URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 결과 저장소 URL
CELERY_ACCEPT_CONTENT = ['json']  # 허용할 콘텐츠 타입
CELERY_TASK_SERIALIZER = 'json'   # 작업 직렬화 방식
CELERY_RESULT_SERIALIZER = 'json' # 결과 직렬화 방식
CELERY_TIMEZONE = TIME_ZONE       # Celery 시간대
