# Generated by Django 6.0 on 2026-01-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='reg_date')),
                ('region', models.CharField(max_length=32)),
                ('division', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('representative', models.CharField(max_length=32)),
                ('business_registration_number', models.CharField(max_length=32)),
                ('number_of_employees', models.IntegerField(default=0)),
                ('annual_sales', models.IntegerField(default=0)),
                ('sectors', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('outsourcing_work_type', models.CharField(max_length=32)),
                ('main_business', models.CharField(max_length=32)),
                ('contract_status', models.CharField(max_length=100)),
                ('v3_contract_status', models.CharField(max_length=2)),
                ('staff_in_charge', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=32)),
                ('erp_maintenance', models.CharField(max_length=10)),
                ('erp_usage_status', models.CharField(max_length=8)),
                ('groupware', models.BooleanField()),
                ('company_evaluation', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '거래처 정보',
                'verbose_name_plural': '거래처 정보들',
                'ordering': ['-registration_date'],
                'constraints': [models.UniqueConstraint(fields=('business_registration_number',), name='unique_business_registration_number')],
            },
        ),
    ]
